### ISSUE TITLE
ed25519 keys support

### ISSUE THREAD

**Issue by foxcpp** [emersion/klaes#2]
```
2020/04/29 19:06:40 openpgp: unsupported feature: public key type: 22
```

IIRC there was a similar issue with hydroxide. Is there any workaround available?

**Comment by emersion** [comment]
Yes, we could switch to ProtonMail's crypto repo: https://github.com/ProtonMail/crypto

**Comment by foxcpp** [comment]
Looks like x/crypto/openpgp is a dependency not only in klaes. Would you accept a patch that simply adds `replace` to go.mod?

**Comment by emersion** [comment]
Yes
